# Generated by Django 5.2 on 2025-04-12 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('journaling', 'Journaling')], max_length=50)),
                ('is_allowed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='allowed_activities_patient', to=settings.AUTH_USER_MODEL)),
                ('therapist', models.ForeignKey(limit_choices_to={'role': 'therapist'}, on_delete=django.db.models.deletion.CASCADE, related_name='allowed_activities_therapist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('therapist', 'patient', 'activity_type')},
            },
        ),
    ]
