# Generated by Django 5.2 on 2025-04-12 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journaling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('resume', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('situation', models.TextField(blank=True, null=True)),
                ('emotions', models.TextField(blank=True, null=True)),
                ('thoughts', models.TextField(blank=True, null=True)),
                ('body_feelings', models.TextField(blank=True, null=True)),
                ('behavior', models.TextField(blank=True, null=True)),
                ('consequences', models.TextField(blank=True, null=True)),
                ('evidence_favorable', models.TextField(blank=True, null=True)),
                ('evidence_unfavorable', models.TextField(blank=True, null=True)),
                ('alternative_thoughts', models.TextField(blank=True, null=True)),
                ('alternative_behaviors', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
